language: cpp

compiler:
  - gcc
  - clang

env:
  matrix:
    - CONF=debug   ARCH=x86_64
    - CONF=release ARCH=x86_64
    - CONF=debug   ARCH=x86
    - CONF=release ARCH=x86
  global:
    - ARCH_FLAGS_x86='-m32'
    - ARCH_FLAGS_x86_64='-msse4.2'


# Before dependencies installation
before_install:
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - sudo add-apt-repository ppa:team-xbmc/ppa -y 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libSDL2-dev cmake
  - if [ "$ARCH" = "x86" ]; then sudo apt-get install -qq g++-multilib libc6-dbg:i386; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - git submodule update --init --recursive

# Dependecies installation
install: true

# Before building
before_script: 
  - lcov --directory . --zerocounters
  - mkdir -p build
  - rm -rf build/*
  - cd build

# Building
script: 
  - cmake ../
  - make

# After building success
after_success: 
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token PGMYIg8qEr1ASI70yft5IwYU1i4cCEX2K coverage.info

# After building failure
after_failure:
  - echo "Building failure !"

# After building in general
# after_script:



