language: cpp

compiler:
  - gcc
  - clang

# Before dependencies installation
before_install:
  - sudo add-apt-repository ppa:team-xbmc/ppa -y 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libSDL2-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - git submodule update --init --recursive

# Dependecies installation
# install: make cmake

# Before building
before_script: 
  - mkdir -p build
  - rm -rf build/*
  - cd build

# Building
script: 
  - cmake ../
  - make

# After building success
after_success: 
  - echo "Building success !"

# After building failure
after_failure:
  - echo "Building failure !"

# After building in general
# after_script:



